### ISSUE TITLE
Not replacing files inside subfolders

### ISSUE THREAD

**Issue by rafaelfragosom** [solidusjs/grunt-filerev-replace#12]
Hi,

The plugin works really well for folders but when it comes to subfolders the files remain the same. I thought it worked because in the docs you have something like `**/*.html` that means it will look for files inside subfolders too.

**Comment by joanniclaborde** [comment]
Maybe you're using wrong relative paths? If you look at the tests, files in subfolders are replaced: https://github.com/solidusjs/grunt-filerev-replace/blob/master/test/fixtures/views/media/index.html -> https://github.com/solidusjs/grunt-filerev-replace/blob/master/test/expected/views/media/index.html
