### ISSUE TITLE
How to change the reference to js/css while using lazyloading js

### ISSUE THREAD

**Issue by zengxiaoting** [solidusjs/grunt-filerev-replace#13]

**Comment by joanniclaborde** [comment]
I don't understand this issue, can you be more specific?

**Comment by zengxiaoting** [comment]
angular.module('app')
  //page deps
  .constant('PAGE_CONFIG', {
      page_home       :   [ 'css/home.css', 'js/controllers/t1-home.js' ],
      page_login      :   [ 'js/controllers/t1-login.js' ],
      page_cart       :   [ 'css/cart.css', 'js/controllers/t1-cart.js' ],
      page_order      :   [ 'css/cart.css', 'js/controllers/t1-order.js' ],
      page_pay        :   [ 'vendor/thirdparty/pingpp/pingpp.js' ]
}

we need to use some constant in angular like above,can't translate the reference to the new one

**Comment by joanniclaborde** [comment]
Maybe you are looking for [grunt-filerev's summary](https://github.com/yeoman/grunt-filerev#summary)?

**Comment by joanniclaborde** [comment]
Please reopen this issue if needed!
