### ISSUE TITLE
Doesn't replace relative paths

### ISSUE THREAD

**Issue by jmtsi** [solidusjs/grunt-filerev-replace#16]
This won't get replaced:
`<div ng-include="'path/to/the/template.html'"></div>`

But this works:
`<div ng-include="'/path/to/the/template.html'"></div>`

My assets_root is 'dist/', and the template is in dist/path/to/the/template.html. The directory dist is in my project root.

**Comment by joanniclaborde** [comment]
The relative paths are computed starting from the path of the view that contains that tag to replace. If that view is not located in the root of the project, we're not able to find it. You'll need to either change the path to something like `../path/to/the/template.html`, or set the `views_root` option.

**Comment by StormPooper** [comment]
@joanniclaborde what would the config look like in this example? We've had a similar problem and couldn't get it to work with `views_root`.

**Comment by joanniclaborde** [comment]
@StormPooper If you look at `Gruntfile.js`, you'll see a working example, used to test `grunt-filerev-replace`. In short, `test/fixtures/` is [copied to `tmp/`](https://github.com/solidusjs/grunt-filerev-replace/blob/master/Gruntfile.js#L31), then [images are filereved](https://github.com/solidusjs/grunt-filerev-replace/blob/master/Gruntfile.js#L35). Now the assets references are replaced in [js and css files](https://github.com/solidusjs/grunt-filerev-replace/blob/master/Gruntfile.js#L44) and [in the views](https://github.com/solidusjs/grunt-filerev-replace/blob/master/Gruntfile.js#L50). Note that the assets are served from `tmp/assets/` and the views are served from `tmp/views/`, so the views need their `views_root` option.

You can also compare the before / after files by looking at `test/fixtures/` and `test/expected/`.

Please reopen the issue if necessary!
