### ISSUE TITLE
grunt-filerev-replace also works for ng-include angularjs directive !?

### ISSUE THREAD

**Issue by Ashrafik** [solidusjs/grunt-filerev-replace#17]
I used "grunt-filerev" and then "grunt-filerev-replace".

Everything is OK but not for html files that contain **ng-include angularjs directive**.
html addresses like:
**ng-include="'app/assets/templates/accounting.html'"** don't replaced.

grunt-filerev-replace just works on **"href"** and **"src"** tags ?
What's the solution for file addresses like ng-include="'app/assets/templates/accounting.html'" ?

**Comment by joanniclaborde** [comment]
This plugin doesn't care about the HTML attribute name, it only looks for paths enclosed in specific delimiters: `'path'`, `"path"` and `(path)`. It also supports absolute and relative paths, for example see the [before](https://github.com/solidusjs/grunt-filerev-replace/blob/master/test/fixtures/views/index.html) and [after](https://github.com/solidusjs/grunt-filerev-replace/blob/master/test/expected/views/index.html) HTML test.

To be sure, I did a local test with `<img ng-include="'images/ajax-loader.gif'" />` and it was replaced correctly to `<img ng-include="'images/ajax-loader.4e26f87c.gif'" />`.

Make sure that the output from `grunt-filerev`, the plugin's options and the relative path are correct. Please reopen this issue if needed!

**Comment by Ashrafik** [comment]
Thanks you, Every thing is OK.
