### ISSUE TITLE
Error: Cannot read property Summary

### ISSUE THREAD

**Issue by dsoldera** [solidusjs/grunt-filerev-replace#18]
Hello,

My plugin is configurated in this way and I´m having this error: 

![grunt-filerev-replace-config](https://cloud.githubusercontent.com/assets/11474555/26369255/80aac788-3fca-11e7-97ee-d41dc4cea397.png)

Error:
![grunt-filerev-replace-error](https://cloud.githubusercontent.com/assets/11474555/26369264/85a4c20c-3fca-11e7-9c42-6453e26d6528.png)

Could you help me how to resolve this?

Thanks

**Comment by joanniclaborde** [comment]
It looks like your `filerev` task is not being run. It needs to be executed before `filerev_replace`, see [here for example](https://github.com/solidusjs/grunt-filerev-replace/blob/master/Gruntfile.js#L73).

**Comment by dsoldera** [comment]
It Works!!! Thanks for the help. =)

**Comment by joanniclaborde** [comment]
👍
