### ISSUE TITLE
Specify targets?

### ISSUE THREAD

**Issue by faustgertz** [solidusjs/grunt-filerev-replace#7]
Is there a way to specify targets? For example:
```
filerev_replace: {
  options: {
    assets_root: '_site/',
  },
  dist: {      
    compiled_assets: {
      src: '_dist/assets/**/*.{css,js}',
    },
    views: {
      options: {
       views_root: '_dist/'
      },
      src: '_dist/**/*.html',
    },
  },      
  local: {      
    compiled_assets: {
      src: '_site/assets/**/*.{css,js}',
    },
    views: {
      options: {
       views_root: '_site/'
      },
      src: '_site/**/*.html',
    },
  },
},
```
to go along with:
```
filerev: {
  options: {
    encoding: 'utf8',
    algorithm: 'md5',
    length: 8
  },
  dist: {
    files: [{
      src: [
        '_dist/assets/js/**/*.js',
        '_dist/assets/css/**/*.css',
        '_dist/assets/img/**/*.{gif,jpg,jpeg,png,svg,webp}',
      ]
    }]
  },
  local: {
    files: [{
      src: [
        '_site/assets/js/**/*.js',
        '_site/assets/css/**/*.css',
        '_site/assets/img/**/*.{gif,jpg,jpeg,png,svg,webp}',
      ]
    }]
  }      
},
```
?

**Comment by joanniclaborde** [comment]
Hmm, grunt-filerev-replace uses [`registerMultiTask`](http://gruntjs.com/creating-tasks#multi-tasks), but I'm now sure I ever tried multiple targets. Feel free to submit a pull request if you find problems!

**Comment by bensventures** [comment]
I believe it does work for multitargets. I am currently using the following config and both tasks get ran correctly.

    filerev_replace: {
        options: {
            assets_root: '<%= assets %>'
        },
        target1: {
            src: '<%= assets %>/dir/assets.conf'
        },
        target2: {
            src: '<%= assets %>/otherdir/assets.conf'
        }
    },

**Comment by joanniclaborde** [comment]
Thanks for your input!
