### ISSUE TITLE
How to remove the root directory sign "/"

### ISSUE THREAD

**Issue by rayzang8** [solidusjs/grunt-filerev-replace#8]
in my case the image path src="img/1.jpg" change to src="/img/1.cb7d442c.jpg"
but I realy want to remain the relative path.

**Comment by joanniclaborde** [comment]
You can try the code in #6, see if it solves your problem. I've meant to merge it into master for a while, haven't had the time yet. If the code works for you too, I'll merge and release a new version soon. Thanks.

**Comment by rayzang8** [comment]
Yes, this code solves my problem!
Thanks for all!

**Comment by joanniclaborde** [comment]
Fixed in 0.1.4.
